export default {
  AUTHENTICATE_ADMIN: 'AUTHENTICATE_ADMIN',
  DEAUTHORIZE: 'DEAUTHORIZE',
  NEW_PARTY_GROUP: 'NEW_PARTY_GROUP',
  GET_LOGINS: 'GET_LOGINS',
  GET_PARTIES: 'GET_PARTIES',
  CLEAR_SELECTED_PARTY: 'CLEAR_SELECTED_PARTY',
  SELECT_PARTY: 'SELECT_PARTY',
  VOTE_FIRST: 'VOTE_FIRST',
  CONFIRM_VOTES: 'CONFIRM_VOTES',
  DELETE_PARTY: 'DELETE_PARTY',
  GET_ADMIN_LOGIN: 'GET_ADMIN_LOGIN',
  CHANGE_ADMIN_USERNAME: 'CHANGE_ADMIN_USERNAME',
  CHANGE_ADMIN_PASSWORD: 'CHANGE_ADMIN_PASSWORD',
  FETCH_PARTY_GROUP: 'FETCH_PARTY_GROUP'
}
